name: Deploy arduino code

on:
  push:
    branches:
      - main

jobs:
  arduino-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ls
      - name: Upload file to FTP server
        uses: matteodf/lftp-upload@v1
        with:
            host: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASS }}
            forceSsl: "false"
            localDir: "/Arduino/arroseur/arroseur.ino"
            remoteDir: "/home/adminMalenia/GreenTeamV2/Arduino/arroseur/arroseur.ino"