name: Deploy arduino code

on:
  push:
    branches:
      - main

jobs:
  arduino-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" -e "
          set ftp:ssl-allow no;
          mirror -R Arduino/arroseur/arroseur.ino /home/adminMalenia/GreenTeamV2/Arduino/arroseur;
          bye
          "   