name: Deploy arduino code

on:
  push:
    branches:
      - main

jobs:
  arduino-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload file to FTP server
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASS }}
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" -e "
          put ./Arduino/arroseur/arroseur.ino -o /home/adminMalenia/GreenTeamV2/Arduino/arroseur/arroseur.ino;
          bye"
        