name: Deploy arduino code

on:
  push:
    tags:
      - "Arduino_v*.*.*"

jobs:
  arduino-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Execute Git Commands on Remote Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/adminMalenia/GreenTeamV2
            git fetch
            git pull
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Arduino/arroseur/arroseur.ino
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${GITHUB_REF_NAME}"