name: Deploy arduino code

on:
  push:
    branches:
      - main

jobs:
  arduino-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" -e "
          set ftp:ssl-allow no;
          set ftp:use-feat no;
          set ftp:passive-mode off;
          mirror -R Arduino/arroseur /home/adminMalenia/GreenTeamV2/Arduino/arroseur;
          bye
          "   